### ISSUE TITLE
[bug] Store中取消订阅无效

### ISSUE THREAD

**Issue by Liuqing650** [le5le-com/le5le-store#2]
在使用 topology 的过程中，由于大部分数据基于此进行管理，我在取消订阅时遇到了一个问题。

取消订阅函数时，实际只删除了 observer 中的对象，下次进入已订阅的页面时任然会执行已取消订阅项，因为被排入到 data 中去了

https://github.com/le5le-com/le5le-store/blob/ef45a041f277efd87193c3791e0a91a797d667c6/src/store/observer.ts#L13-L15

**Comment by Alsmile** [comment]
已更新： le5le-store@1.0.3
